name: Release CI

on:
  push:
    branches:
      - master

env:
  PLATFORM: linux/amd64
  DOCKER_REPO: renovate/buildpack
  DOCKER_CACHE: buildpack
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - name: docker cache
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker images
        run: |
          cache_from=$([ -d .cache ] && echo -n '--cache-from=type=local,src=.cache' || echo -n '')
          docker buildx build \
            --load \
            --tag ${DOCKER_REPO} \
            --cache-to=type=registry,ref=renovate/docker-build-cache:${DOCKER_CACHE},mode=max \
            --cache-from=renovate/docker-build-cache:${DOCKER_CACHE} \
            $cache_from \
            .

      - name: Test the Docker images
        run: docker run --rm -t ${DOCKER_REPO} git --version

      - name: Publish
        uses: renovatebot/gh-action@v0
        with:
          command: "publish-docker"
          image: ${{ env.DOCKER_REPO }}
          tags: latest
          dry-run: ${{github.ref != 'refs/heads/master'}}